"""Add printable column

Revision ID: 168ddfd45528
Revises: 
Create Date: 2017-09-27 19:10:35.719134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168ddfd45528'
down_revision = None
branch_labels = ('resume',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_item', sa.Column('printable', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('hobby', sa.Column('printable', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('job_experience', sa.Column('printable', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('language', sa.Column('printable', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('life_experience', sa.Column('printable', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('skill', sa.Column('printable', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'printable')
    op.drop_column('life_experience', 'printable')
    op.drop_column('language', 'printable')
    op.drop_column('job_experience', 'printable')
    op.drop_column('hobby', 'printable')
    op.drop_column('contact_item', 'printable')
    # ### end Alembic commands ###
