"""Add priority to resume elements

Revision ID: f131f027acfe
Revises: 0904da817363
Create Date: 2017-09-28 22:31:14.071791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f131f027acfe'
down_revision = '168ddfd45528'
branch_labels = ('resume',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'street_two',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('contact_item', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('hobby', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_experience', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('language', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('life_experience', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('skill', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'priority')
    op.drop_column('life_experience', 'priority')
    op.drop_column('language', 'priority')
    op.drop_column('job_experience', 'priority')
    op.drop_column('hobby', 'priority')
    op.drop_column('contact_item', 'priority')
    op.alter_column('address', 'street_two',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
